import React from 'react'
import getDataFromPatientInterface from '../../utils/getDataFromPatientInterface'
import { dbLabels } from '../../constants'
import { GlandComponentProps } from '../../types'
import ConditionalCheckboxOption from './conditional-checkbox-option'
import ConditionalCheckboxes from './conditional-checkboxes'
import SimpleCheckboxes from './simple-checkboxes'
import TextInput from './text-input'
import NumberInput from './number-input'
import { useTranslation } from 'react-i18next'
import { formTranslationKeys } from '../../translations'

const HistopathologyMalignant: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()

    return (
        <div className="sectionDiv">
            <h1>{t(formTranslationKeys.histopathology)}</h1>
            <h2>{t(formTranslationKeys.histologicalType)}</h2>
            <ConditionalCheckboxes
                dbLabel={dbLabels.histopatologie_vysledek}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.acinicCellCarcinoma)}
                    dbValue="acinic-cell-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.secretoryCarcinoma)}
                    dbValue="secretory-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.mucoepidermoidCarcinoma)}
                    dbValue="mucoepidermoid-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.mukoepidermoidni_karcinom_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.lowGrade,
                            formTranslationKeys.intermediateGrade,
                            formTranslationKeys.highGrade,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                        translate={true}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.adenoidCysticCarcinoma)}
                    dbValue="adenoid-cystic-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.adenoidne_cysticky_karcinom_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.tubularCribriformDominant,
                            formTranslationKeys.moreThan30SolidComponent,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.polymorphousAdenocarcinoma)}
                    dbValue="polymorphous-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.polymorfni_adenokarcinom_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.classic,
                            formTranslationKeys.cribriform,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(
                        formTranslationKeys.epithelialMyoepithelialCarcinoma
                    )}
                    dbValue="epithelial-myoepithelial-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.hyalinizingClearCellCarcinoma)}
                    dbValue="hyalinizing-clear-cell-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.basalCellAdenocarcinoma)}
                    dbValue="basal-cell-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.sebaceousAdenocarcinoma)}
                    dbValue="sebaceous-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.intraductalCarcinoma)}
                    dbValue="intraductal-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={dbLabels.intraduktalni_karcinom_histopatologie}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.intercalatedDuctLike,
                            formTranslationKeys.apocrine,
                            formTranslationKeys.oncocytic,
                            formTranslationKeys.mixed,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.salivaryCarcinomaNos)}
                    dbValue="salivary-carcinoma-nos"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={dbLabels.salivarni_karcinom_nos_histopatologie}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.oncocyticAdenocarcinoma,
                            formTranslationKeys.intestinalTypeAdenocarcinoma,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.salivaryDuctCarcinoma)}
                    dbValue="salivary-duct-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.myoepithelialCarcinoma)}
                    dbValue="myoepithelial-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.carcinomaExPleomorphicAdenoma)}
                    dbValue="carcinoma-ex-pleomorphic-adenoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.karcinom_z_pleomorfniho_adenomu_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.intracapsular,
                            formTranslationKeys.minimallyInvasive,
                            formTranslationKeys.invasive,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.carcinosarcoma)}
                    dbValue="carcinosarcoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.poorlyDifferentiatedCarcinoma)}
                    dbValue="poorly-differentiated-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.spatne_diferencovany_karcinom_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            formTranslationKeys.undifferentiatedCarcinoma,
                            formTranslationKeys.largeCellNeuroendocrineCarcinoma,
                            formTranslationKeys.smallCellNeuroendocrineCarcinoma,
                            formTranslationKeys.subtypeNotSpecified,
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.lymphoepithelialCarcinoma)}
                    dbValue="lymphoepithelial-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.squamousCellCarcinoma)}
                    dbValue="squamous-cell-carcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.microsecretoryAdenocarcinoma)}
                    dbValue="microsecretory-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(
                        formTranslationKeys.sclerosingMicrocysticAdenocarcinoma
                    )}
                    dbValue="sclerosing-microcystic-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.mucinousAdenocarcinoma)}
                    dbValue="mucinous-adenocarcinoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.asialoblastoma)}
                    dbValue="asialoblastoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.maltLymphoma)}
                    dbValue="malt-lymphoma"
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.other)}
                    dbValue="other"
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>

            <h2>{t(formTranslationKeys.histologicalTypeSpecification)}</h2>

            <NumberInput
                label={t(formTranslationKeys.tumorSizeLargestDimension)}
                dbLabel={dbLabels.velikost_nadoru_histopatologie}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.velikost_nadoru_histopatologie
                )}
                setFormData={setFormData}
                disabled={disabled}
            />

            <TextInput
                label={t(formTranslationKeys.tumorSizeNotDeterminedExplain)}
                dbLabel={dbLabels.velikost_nadoru_neurcena_histopatologie}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.velikost_nadoru_neurcena_histopatologie
                )}
                setFormData={setFormData}
                disabled={disabled}
            />

            <SimpleCheckboxes
                title={t(formTranslationKeys.resectionMargin)}
                dbLabel={dbLabels.okraj_resekce_histopatologie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[t(formTranslationKeys.r0), t(formTranslationKeys.r1)]}
                disabled={disabled}
            />

            <SimpleCheckboxes
                title={t(formTranslationKeys.lymphovascularInvasion)}
                dbLabel={dbLabels.lymfovaskularni_invaze_histopatologie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.no),
                    t(formTranslationKeys.yes),
                ]}
                disabled={disabled}
            />

            <SimpleCheckboxes
                title={t(formTranslationKeys.perineuralInvasion)}
                dbLabel={dbLabels.perineuralni_invaze_histopatologie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.no),
                    t(formTranslationKeys.yes),
                ]}
                disabled={disabled}
            />

            <NumberInput
                label={t(formTranslationKeys.numberOfLymphNodesWithMetastasis)}
                dbLabel={
                    dbLabels.pocet_lymfatickych_uzlin_s_metastazou_histopatologie
                }
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.pocet_lymfatickych_uzlin_s_metastazou_histopatologie
                )}
                setFormData={setFormData}
                disabled={disabled}
            />

            <ConditionalCheckboxes
                title={t(formTranslationKeys.extranodalSpreadEne)}
                dbLabel={dbLabels.extranodalni_sireni_histopatologie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        dbLabel={
                            dbLabels.extranodalni_sireni_vysledek_histopatologie
                        }
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t(formTranslationKeys.ENEmaOver2mm),
                            t(formTranslationKeys.ENEmi2mmOrLess),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
            </ConditionalCheckboxes>

            <ConditionalCheckboxes
                title={t(formTranslationKeys.provenDistantMetastases)}
                dbLabel={dbLabels.prokazane_vzdalene_metastazy_histopatologie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <TextInput
                        label={t(
                            formTranslationKeys.specifySiteOfDistantMetastasis
                        )}
                        dbLabel={
                            dbLabels.misto_vyskytu_vzdalene_metastazy_histopatologie
                        }
                        data={getDataFromPatientInterface(
                            formData,
                            dbLabels.misto_vyskytu_vzdalene_metastazy_histopatologie
                        )}
                        setFormData={setFormData}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
            </ConditionalCheckboxes>
        </div>
    )
}

export default HistopathologyMalignant
