export class HistologyTypeMapper {
    static mapKeyToId(key: string): number | undefined {
        const mapping: { [key: string]: number } = {
            'acinic-cell-carcinoma': 1,
            'secretory-carcinoma': 2,
            'mucoepidermoid-carcinoma': 3,
            'adenoid-cystic-carcinoma': 4,
            'polymorphous-adenocarcinoma': 5,
            'epithelial-myoepithelial-carcinoma': 6,
            'hyalinizing-clear-cell-carcinoma': 7,
            'basal-cell-adenocarcinoma': 8,
            'sebaceous-adenocarcinoma': 9,
            'intraductal-carcinoma': 10,
            'salivary-carcinoma-nos': 11,
            'salivary-duct-carcinoma': 12,
            'myoepithelial-carcinoma': 13,
            'carcinoma-ex-pleomorphic-adenoma': 14,
            carcinosarcoma: 15,
            'poorly-differentiated-carcinoma': 16,
            'lymphoepithelial-carcinoma': 17,
            'squamous-cell-carcinoma': 18,
            'microsecretory-adenocarcinoma': 19,
            'sclerosing-microcystic-adenocarcinoma': 20,
            'mucinous-adenocarcinoma': 21,
            asialoblastoma: 22,
            'malt-lymphoma': 23,
            other: 24,
            'pleomorphic-adenoma': 25,
            'warthin-tumor': 26,
            'basal-cell-adenoma': 27,
            myoepithelioma: 28,
            oncocytoma: 29,
            'canalicular-adenoma': 30,
            'sebaceous-adenoma': 31,
            'ductal-papilloma': 32,
            'sebaceous-lymphadenoma': 33,
            keratocystoma: 34,
        }

        return mapping[key] || undefined
    }

    static mapIdToKey(id: number): string | null {
        const mapping: { [key: number]: string } = {
            1: 'acinic-cell-carcinoma',
            2: 'secretory-carcinoma',
            3: 'mucoepidermoid-carcinoma',
            4: 'adenoid-cystic-carcinoma',
            5: 'polymorphous-adenocarcinoma',
            6: 'epithelial-myoepithelial-carcinoma',
            7: 'hyalinizing-clear-cell-carcinoma',
            8: 'basal-cell-adenocarcinoma',
            9: 'sebaceous-adenocarcinoma',
            10: 'intraductal-carcinoma',
            11: 'salivary-carcinoma-nos',
            12: 'salivary-duct-carcinoma',
            13: 'myoepithelial-carcinoma',
            14: 'carcinoma-ex-pleomorphic-adenoma',
            15: 'carcinosarcoma',
            16: 'poorly-differentiated-carcinoma',
            17: 'lymphoepithelial-carcinoma',
            18: 'squamous-cell-carcinoma',
            19: 'microsecretory-adenocarcinoma',
            20: 'sclerosing-microcystic-adenocarcinoma',
            21: 'mucinous-adenocarcinoma',
            22: 'asialoblastoma',
            23: 'malt-lymphoma',
            24: 'other',
            25: 'pleomorphic-adenoma',
            26: 'warthin-tumor',
            27: 'basal-cell-adenoma',
            28: 'myoepithelioma',
            29: 'oncocytoma',
            30: 'canalicular-adenoma',
            31: 'sebaceous-adenoma',
            32: 'ductal-papilloma',
            33: 'sebaceous-lymphadenoma',
            34: 'keratocystoma',
            35: 'other',
        }

        return mapping[id] || null
    }
}
