import React from 'react'
import { GlandComponentProps } from '../../../../types'
import { dbLabels } from '../../../../constants'
import DatePicker from '../../date-picker'
import getDataFromPatientInterface from '../../../../utils/getDataFromPatientInterface'
import SimpleCheckboxes from '../../simple-checkboxes'
import ConditionalCheckboxes from '../../conditional-checkboxes'
import ConditionalCheckboxOption from '../../conditional-checkbox-option'
import TextInput from '../../text-input'
import { useTranslation } from 'react-i18next'
import {
    formTranslationKeys,
    appTranslationKeys,
} from '../../../../translations'

const ParotidBenignGlandDiagnosis: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()

    return (
        <div className="sectionDiv">
            <h1>{t(formTranslationKeys.diagnosisTitle)}</h1>
            <DatePicker
                label={t(formTranslationKeys.yearOfDiagnosis)}
                dbLabel={dbLabels.rok_diagnozy}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.rok_diagnozy
                )}
                setFormData={setFormData}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.sideOfFinding)}
                dbLabel={dbLabels.strana_nalezu}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.sideRight),
                    t(formTranslationKeys.sideLeft),
                    t(formTranslationKeys.bilateraly),
                ]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.nVIIFunctionHBPreOp)}
                dbLabel={dbLabels.funkce_n_vii_dle_h_b_predoperacne}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['I', 'II', 'III', 'IV', 'V', 'VI']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosticMethods)}
                dbLabel={dbLabels.diagnosticke_metody}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={false}
                options={[
                    t(formTranslationKeys.methodUz),
                    t(formTranslationKeys.methodCt),
                    t(formTranslationKeys.methodMri),
                    t(formTranslationKeys.methodPetCt),
                    t(formTranslationKeys.methodPetMr),
                    t(formTranslationKeys.noImagingPerformed),
                ]}
                disabled={disabled}
            />
            <ConditionalCheckboxes
                title={t(formTranslationKeys.fnab)}
                dbLabel={dbLabels.fnab}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        title={t(formTranslationKeys.fnabResultMSRSGC)}
                        dbLabel={dbLabels.vysledek_fnab}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t(formTranslationKeys.fnabResultI),
                            t(formTranslationKeys.fnabResultII),
                            t(formTranslationKeys.atypiaUnspecified),
                            t(formTranslationKeys.IVaTumorBenign),
                            t(formTranslationKeys.uncertainMalignantPotential),
                            t(formTranslationKeys.suspectedMalignancy),
                            t(appTranslationKeys.malignantTumor),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.coreBiopsy)}
                dbLabel={dbLabels.core_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.coreBiopsyResult)}
                        dbLabel={dbLabels.core_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultPleomorphicAdenoma
                            )}
                            dbValue="pleomorphic-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultWarthinTumor
                            )}
                            dbValue="warthin-tumor"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultBasalCellAdenoma
                            )}
                            dbValue="basal-cell-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultMyoepithelioma
                            )}
                            dbValue="myoepithelioma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.coreResultOncocytoma)}
                            dbValue="oncocytoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultCanalicularAdenoma
                            )}
                            dbValue="canalicular-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultSebaceousAdenoma
                            )}
                            dbValue="sebaceous-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.ductalPapilloma)}
                            dbValue="ductal-papilloma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultSebaceousLymphadenoma
                            )}
                            dbValue="sebaceous-lymphadenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultKeratocystoma
                            )}
                            dbValue="keratocystoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(appTranslationKeys.other)}
                            dbValue="other"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <TextInput
                                label={t(
                                    formTranslationKeys.histologicalTypeSpecification
                                )}
                                dbLabel={dbLabels.core_vysledek_jine}
                                data={getDataFromPatientInterface(
                                    formData,
                                    dbLabels.core_vysledek_jine
                                )}
                                setFormData={setFormData}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.openBiopsy)}
                dbLabel={dbLabels.otevrena_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.openBiopsyResult)}
                        dbLabel={dbLabels.otevrena_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultPleomorphicAdenoma
                            )}
                            dbValue="pleomorphic-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultWarthinTumor
                            )}
                            dbValue="warthin-tumor"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultBasalCellAdenoma
                            )}
                            dbValue="basal-cell-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultMyoepithelioma
                            )}
                            dbValue="myoepithelioma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.coreResultOncocytoma)}
                            dbValue="oncocytoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultCanalicularAdenoma
                            )}
                            dbValue="canalicular-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultSebaceousAdenoma
                            )}
                            dbValue="sebaceous-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.ductalPapilloma)}
                            dbValue="ductal-papilloma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultSebaceousLymphadenoma
                            )}
                            dbValue="sebaceous-lymphadenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultKeratocystoma
                            )}
                            dbValue="keratocystoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(appTranslationKeys.other)}
                            dbValue="other"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <TextInput
                                label={t(
                                    formTranslationKeys.histologicalTypeSpecification
                                )}
                                dbLabel={dbLabels.otevrena_vysledek_jine}
                                data={getDataFromPatientInterface(
                                    formData,
                                    dbLabels.otevrena_vysledek_jine
                                )}
                                setFormData={setFormData}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(appTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
        </div>
    )
}

export default ParotidBenignGlandDiagnosis
