import React from 'react'
import { dbLabels } from '../../../../constants'
import { GlandComponentProps } from '../../../../types'
import getDataFromPatientInterface from '../../../../utils/getDataFromPatientInterface'
import ConditionalCheckboxOption from '../../conditional-checkbox-option'
import ConditionalCheckboxes from '../../conditional-checkboxes'
import DatePicker from '../../date-picker'
import SimpleCheckboxes from '../../simple-checkboxes'
import { useTranslation } from 'react-i18next'
import { formTranslationKeys } from '../../../../translations'

const SubmandibularMalignantGlandDiagnosis: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()

    return (
        <div className="sectionDiv">
            <h1>{t(formTranslationKeys.diagnosisTitle)}</h1>
            <DatePicker
                label={t(formTranslationKeys.yearOfDiagnosis)}
                dbLabel={dbLabels.rok_diagnozy}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.rok_diagnozy
                )}
                setFormData={setFormData}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosisIcd10)}
                dbLabel={dbLabels.diagnoza_mkn_10}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['C080']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.sideOfFinding)}
                dbLabel={dbLabels.strana_nalezu}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.sideRight),
                    t(formTranslationKeys.sideLeft),
                    t(formTranslationKeys.bilateraly),
                ]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.nVIIFunctionHBPreOp)}
                dbLabel={dbLabels.funkce_n_vii_dle_h_b_predoperacne}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['I', 'II', 'III', 'IV', 'V', 'VI']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosticMethodsUsed)}
                dbLabel={dbLabels.diagnosticke_metody}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={false}
                options={[
                    t(formTranslationKeys.methodUz),
                    t(formTranslationKeys.ct),
                    t(formTranslationKeys.mri),
                    t(formTranslationKeys.petCt),
                    t(formTranslationKeys.petMr),
                    t(formTranslationKeys.noImagingPerformed),
                ]}
                disabled={disabled}
            />
            <ConditionalCheckboxes
                title={t(formTranslationKeys.fnab)}
                dbLabel={dbLabels.fnab}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                disabled={disabled}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        title={t(formTranslationKeys.fnabResultMSRSGC)}
                        dbLabel={dbLabels.vysledek_fnab}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t(formTranslationKeys.fnabResultI),
                            t(formTranslationKeys.fnabResultII),
                            t(formTranslationKeys.atypiaUnspecified),
                            t(formTranslationKeys.IVaTumorBenign),
                            t(formTranslationKeys.uncertainMalignantPotential),
                            t(formTranslationKeys.suspectedMalignancy),
                            t(formTranslationKeys.VITumorMalignant),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.coreBiopsy)}
                dbLabel={dbLabels.core_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                disabled={disabled}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.coreBiopsyResult)}
                        dbLabel={dbLabels.core_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        disabled={disabled}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.acinocellularCarcinoma
                            )}
                            dbValue="acinic-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.secretoryCarcinoma)}
                            dbValue="secretory-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucoepidermoidCarcinoma
                            )}
                            dbValue="mucoepidermoid-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.lowGrade,
                                    formTranslationKeys.intermediateGrade,
                                    formTranslationKeys.highGrade,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.adenoidCysticCarcinoma
                            )}
                            dbValue="adenoid-cystic-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.tubularCribriformDominant,
                                    formTranslationKeys.moreThan30SolidComponent,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.polymorphousAdenocarcinoma
                            )}
                            dbValue="polymorphous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.polymorfni_adenokarcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.classic,
                                    formTranslationKeys.cribriform,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.epithelialMyoepithelialCarcinoma
                            )}
                            dbValue="epithelial-myoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.hyalinizingClearCellCarcinoma
                            )}
                            dbValue="hyalinizing-clear-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.basalCellAdenocarcinoma
                            )}
                            dbValue="basal-cell-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sebaceousAdenocarcinoma
                            )}
                            dbValue="sebaceous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.intraductalCarcinoma)}
                            dbValue="intraductal-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.intraduktalni_karcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.intercalatedDuctLike,
                                    formTranslationKeys.apocrine,
                                    formTranslationKeys.oncocytic,
                                    formTranslationKeys.mixed,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryCarcinomaNos)}
                            dbValue="salivary-carcinoma-nos"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.salivarni_karcinom_nos_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.oncocyticAdenocarcinoma,
                                    formTranslationKeys.intestinalTypeAdenocarcinoma,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.salivaryDuctalCarcinoma
                            )}
                            dbValue="salivary-duct-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.myoepithelialCarcinoma
                            )}
                            dbValue="myoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.carcinomaExPleomorphicAdenoma
                            )}
                            dbValue="carcinoma-ex-pleomorphic-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.intracapsular,
                                    formTranslationKeys.minimallyInvasive,
                                    formTranslationKeys.invasive,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.carcinosarcoma)}
                            dbValue="carcinosarcoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.poorlyDifferentiatedCarcinoma
                            )}
                            dbValue="poorly-differentiated-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.undifferentiatedCarcinoma,
                                    formTranslationKeys.largeCellNeuroendocrineCarcinoma,
                                    formTranslationKeys.smallCellNeuroendocrineCarcinoma,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.lymphoepithelialCarcinoma
                            )}
                            dbValue="lymphoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.squamousCellCarcinoma)}
                            dbValue="squamous-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.microsecretoryAdenocarcinoma
                            )}
                            dbValue="microsecretory-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sclerosingMicrocysticAdenocarcinoma
                            )}
                            dbValue="sclerosing-microcystic-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucinousAdenocarcinoma
                            )}
                            dbValue="mucinous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sialoblastoma')}
                            dbValue="asialoblastoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.maltLymphoma)}
                            dbValue="malt-lymphoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.other)}
                            dbValue="other"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.openBiopsy)}
                dbLabel={dbLabels.otevrena_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                disabled={disabled}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.openBiopsyResult)}
                        dbLabel={dbLabels.otevrena_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        disabled={disabled}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.acinocellularCarcinoma
                            )}
                            dbValue="acinic-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.secretoryCarcinoma)}
                            dbValue="secretory-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucoepidermoidCarcinoma
                            )}
                            dbValue="mucoepidermoid-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.lowGrade,
                                    formTranslationKeys.intermediateGrade,
                                    formTranslationKeys.highGrade,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.adenoidCysticCarcinoma
                            )}
                            dbValue="adenoid-cystic-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.tubularCribriformDominant,
                                    formTranslationKeys.moreThan30SolidComponent,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.polymorphousAdenocarcinoma
                            )}
                            dbValue="polymorphous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.polymorfni_adenokarcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.classic,
                                    formTranslationKeys.cribriform,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.epithelialMyoepithelialCarcinoma
                            )}
                            dbValue="epithelial-myoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.hyalinizingClearCellCarcinoma
                            )}
                            dbValue="hyalinizing-clear-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.basalCellAdenocarcinoma
                            )}
                            dbValue="basal-cell-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sebaceousAdenocarcinoma
                            )}
                            dbValue="sebaceous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.intraductalCarcinoma)}
                            dbValue="intraductal-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.intraduktalni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.intercalatedDuctLike,
                                    formTranslationKeys.apocrine,
                                    formTranslationKeys.oncocytic,
                                    formTranslationKeys.mixed,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryCarcinomaNos)}
                            dbValue="salivary-carcinoma-nos"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.salivarni_karcinom_nos_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.oncocyticAdenocarcinoma,
                                    formTranslationKeys.intestinalTypeAdenocarcinoma,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.salivaryDuctalCarcinoma
                            )}
                            dbValue="salivary-duct-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.myoepithelialCarcinoma
                            )}
                            dbValue="myoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.carcinomaExPleomorphicAdenoma
                            )}
                            dbValue="carcinoma-ex-pleomorphic-adenoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.intracapsular,
                                    formTranslationKeys.minimallyInvasive,
                                    formTranslationKeys.invasive,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.carcinosarcoma)}
                            dbValue="carcinosarcoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.poorlyDifferentiatedCarcinoma
                            )}
                            dbValue="poorly-differentiated-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    formTranslationKeys.undifferentiatedCarcinoma,
                                    formTranslationKeys.largeCellNeuroendocrineCarcinoma,
                                    formTranslationKeys.smallCellNeuroendocrineCarcinoma,
                                    formTranslationKeys.subtypeNotSpecified,
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.lymphoepithelialCarcinoma
                            )}
                            dbValue="lymphoepithelial-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.squamousCellCarcinoma)}
                            dbValue="squamous-cell-carcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.microsecretoryAdenocarcinoma
                            )}
                            dbValue="microsecretory-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sclerosingMicrocysticAdenocarcinoma
                            )}
                            dbValue="sclerosing-microcystic-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucinousAdenocarcinoma
                            )}
                            dbValue="mucinous-adenocarcinoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sialoblastoma')}
                            dbValue="asialoblastoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.maltLymphoma)}
                            dbValue="malt-lymphoma"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.other)}
                            dbValue="other"
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
        </div>
    )
}

export default SubmandibularMalignantGlandDiagnosis
