import React from 'react'
import { GlandComponentProps } from '../../../../types'
import { dbLabels } from '../../../../constants'
import DatePicker from '../../date-picker'
import getDataFromPatientInterface from '../../../../utils/getDataFromPatientInterface'
import SimpleCheckboxes from '../../simple-checkboxes'
import ConditionalCheckboxes from '../../conditional-checkboxes'
import ConditionalCheckboxOption from '../../conditional-checkbox-option'
import { useTranslation } from 'react-i18next'
import { formTranslationKeys } from '../../../../translations'
const ParotidMalignantGlandDiagnosis: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()

    return (
        <div className="sectionDiv">
            <h1>{t(formTranslationKeys.diagnosisTitle)}</h1>
            <DatePicker
                label={t(formTranslationKeys.yearOfDiagnosis)}
                dbLabel={dbLabels.rok_diagnozy}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.rok_diagnozy
                )}
                setFormData={setFormData}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosisIcd10)}
                dbLabel={dbLabels.diagnoza_mkn_10}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['C07']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.sideOfFinding)}
                dbLabel={dbLabels.strana_nalezu}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.sideRight),
                    t(formTranslationKeys.sideLeft),
                    t(formTranslationKeys.bilateraly),
                ]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.nVIIFunctionHBPreOp)}
                dbLabel={dbLabels.funkce_n_vii_dle_h_b_predoperacne}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.I),
                    t(formTranslationKeys.II),
                    t(formTranslationKeys.III),
                    t(formTranslationKeys.IV),
                    t(formTranslationKeys.V),
                    t(formTranslationKeys.VI),
                ]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosticMethodsUsed)}
                dbLabel={dbLabels.diagnosticke_metody}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={false}
                options={[
                    t(formTranslationKeys.methodUz),
                    t(formTranslationKeys.methodCt),
                    t(formTranslationKeys.methodMri),
                    t(formTranslationKeys.methodPetCt),
                    t(formTranslationKeys.methodPetMr),
                    t(formTranslationKeys.noImagingPerformed),
                ]}
                disabled={disabled}
            />
            <ConditionalCheckboxes
                title={t(formTranslationKeys.fnab)}
                dbLabel={dbLabels.fnab}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        title={t(formTranslationKeys.fnabResultMSRSGC)}
                        dbLabel={dbLabels.vysledek_fnab}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t(formTranslationKeys.fnabResultI),
                            t(formTranslationKeys.fnabResultII),
                            t(formTranslationKeys.atypiaUnspecified),
                            t(formTranslationKeys.IVaTumorBenign),
                            t(formTranslationKeys.uncertainMalignantPotential),
                            t(formTranslationKeys.suspectedMalignancy),
                            t(formTranslationKeys.VITumorMalignant),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.coreBiopsy)}
                dbLabel={dbLabels.core_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.coreBiopsyResult)}
                        dbLabel={dbLabels.core_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.acinocellularCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.secretoryCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucoepidermoidCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.lowGrade),
                                    t(formTranslationKeys.intermediateGrade),
                                    t(formTranslationKeys.highGrade),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.adenoidCysticCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.tubularCribriformDominant
                                    ),
                                    t(
                                        formTranslationKeys.moreThan30SolidComponent
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.polymorphousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.polymorfni_adenokarcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.classic),
                                    t(formTranslationKeys.cribriform),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.epithelialMyoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.hyalinizingClearCellCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.basalCellAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sebaceousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.intraductalCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.intraduktalni_karcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.intercalatedDuctLike),
                                    t(formTranslationKeys.apocrine),
                                    t(formTranslationKeys.oncocytic),
                                    t(formTranslationKeys.mixed),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryCarcinomaNos)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.salivarni_karcinom_nos_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.oncocyticAdenocarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.intestinalTypeAdenocarcinoma
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryDuctCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.myoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.carcinomaExPleomorphicAdenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.intracapsular),
                                    t(formTranslationKeys.minimallyInvasive),
                                    t(formTranslationKeys.invasive),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.carcinosarcoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.poorlyDifferentiatedCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.undifferentiatedCarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.largeCellNeuroendocrineCarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.smallCellNeuroendocrineCarcinoma
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.lymphoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.squamousCellCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.microsecretoryAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sclerosingMicrocysticAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucinousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.asialoblastoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.maltLymphoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.other)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.openBiopsy)}
                dbLabel={dbLabels.otevrena_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.openBiopsyResult)}
                        dbLabel={dbLabels.otevrena_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.acinocellularCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.secretoryCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucoepidermoidCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.lowGrade),
                                    t(formTranslationKeys.intermediateGrade),
                                    t(formTranslationKeys.highGrade),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.adenoidCysticCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.tubularCribriformDominant
                                    ),
                                    t(
                                        formTranslationKeys.moreThan30SolidComponent
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.polymorphousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.polymorfni_adenokarcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.classic),
                                    t(formTranslationKeys.cribriform),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.epithelialMyoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.hyalinizingClearCellCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.basalCellAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sebaceousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.intraductalCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.intraduktalni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.intercalatedDuctLike),
                                    t(formTranslationKeys.apocrine),
                                    t(formTranslationKeys.oncocytic),
                                    t(formTranslationKeys.mixed),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryCarcinomaNos)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.salivarni_karcinom_nos_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.oncocyticAdenocarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.intestinalTypeAdenocarcinoma
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.salivaryDuctCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.myoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.carcinomaExPleomorphicAdenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(formTranslationKeys.intracapsular),
                                    t(formTranslationKeys.minimallyInvasive),
                                    t(formTranslationKeys.invasive),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.carcinosarcoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.poorlyDifferentiatedCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t(
                                        formTranslationKeys.undifferentiatedCarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.largeCellNeuroendocrineCarcinoma
                                    ),
                                    t(
                                        formTranslationKeys.smallCellNeuroendocrineCarcinoma
                                    ),
                                    t(formTranslationKeys.subtypeNotSpecified),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.lymphoepithelialCarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.squamousCellCarcinoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.microsecretoryAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.sclerosingMicrocysticAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.mucinousAdenocarcinoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.asialoblastoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.maltLymphoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
        </div>
    )
}

export default ParotidMalignantGlandDiagnosis
