import React from 'react'
import { GlandComponentProps } from '../../../../types'
import { dbLabels } from '../../../../constants'
import DatePicker from '../../date-picker'
import getDataFromPatientInterface from '../../../../utils/getDataFromPatientInterface'
import SimpleCheckboxes from '../../simple-checkboxes'
import ConditionalCheckboxes from '../../conditional-checkboxes'
import ConditionalCheckboxOption from '../../conditional-checkbox-option'
import { useTranslation } from 'react-i18next'

const ParotidMalignantGlandDiagnosis: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()
    return (
        <div className="sectionDiv">
            <h1>{t('diagnosis-title')}</h1>
            <DatePicker
                label={t('year-of-diagnosis')}
                dbLabel={dbLabels.rok_diagnozy}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.rok_diagnozy
                )}
                setFormData={setFormData}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t('diagnosis-icd-10')}
                dbLabel={dbLabels.diagnoza_mkn_10}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['C07']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t('side-of-finding')}
                dbLabel={dbLabels.strana_nalezu}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[t('side-right'), t('side-left'), t('bilateraly')]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t('n-vii-function-hb-pre-op')}
                dbLabel={dbLabels.funkce_n_vii_dle_h_b_predoperacne}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[t('I'), t('II'), t('III'), t('IV'), t('V'), t('VI')]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t('diagnostic-methods-used')}
                dbLabel={dbLabels.diagnosticke_metody}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={false}
                options={[
                    t('method-uz'),
                    t('method-ct'),
                    t('method-mri'),
                    t('method-pet-ct'),
                    t('method-pet-mr'),
                    t('no-imaging-performed'),
                ]}
                disabled={disabled}
            />
            <ConditionalCheckboxes
                title={t('fnab')}
                dbLabel={dbLabels.fnab}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t('yes')}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        title={t('fnab-result-MSRSGC')}
                        dbLabel={dbLabels.vysledek_fnab}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t('fnab-result-i'),
                            t('fnab-result-ii'),
                            t('atypia-unspecified'),
                            t('IVa-tumor-benign'),
                            t('uncertain-malignant-potential'),
                            t('suspected-malignancy'),
                            t('VI-tumor-malignant'),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t('no')}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t('core-biopsy')}
                dbLabel={dbLabels.core_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t('yes')}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t('core-biopsy-result')}
                        dbLabel={dbLabels.core_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t('acinocellular-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('secretory-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('mucoepidermoid-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('low-grade'),
                                    t('intermediate-grade'),
                                    t('high-grade'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('adenoid-cystic-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('tubular-cribriform-dominant'),
                                    t('more-than-30-solid-component'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('polymorphous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.polymorfni_adenokarcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('classic'),
                                    t('cribriform'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('epithelial-myoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('hyalinizing-clear-cell-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('basal-cell-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sebaceous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('intraductal-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.intraduktalni_karcinom_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('intercalated-duct-like'),
                                    t('apocrine'),
                                    t('oncocytic'),
                                    t('mixed'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('salivary-carcinoma-nos')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={dbLabels.salivarni_karcinom_nos_core}
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('oncocytic-adenocarcinoma'),
                                    t('intestinal-type-adenocarcinoma'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('salivary-duct-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('myoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('carcinoma-ex-pleomorphic-adenoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('intracapsular'),
                                    t('minimally-invasive'),
                                    t('invasive'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('carcinosarcoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('poorly-differentiated-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_core
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('undifferentiated-carcinoma'),
                                    t('large-cell-neuroendocrine-carcinoma'),
                                    t('small-cell-neuroendocrine-carcinoma'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('lymphoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('squamous-cell-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('microsecretory-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sclerosing-microcystic-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('mucinous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('asialoblastoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('malt-lymphoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('other')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t('no')}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t('open-biopsy')}
                dbLabel={dbLabels.otevrena_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t('yes')}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t('open-biopsy-result')}
                        dbLabel={dbLabels.otevrena_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t('acinocellular-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('secretory-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('mucoepidermoid-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.mukoepidermoidni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('low-grade'),
                                    t('intermediate-grade'),
                                    t('high-grade'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('adenoid-cystic-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.adenoidne_cysticky_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('tubular-cribriform-dominant'),
                                    t('more-than-30-solid-component'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('polymorphous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.polymorfni_adenokarcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('classic'),
                                    t('cribriform'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('epithelial-myoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('hyalinizing-clear-cell-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('basal-cell-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sebaceous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('intraductal-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.intraduktalni_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('intercalated-duct-like'),
                                    t('apocrine'),
                                    t('oncocytic'),
                                    t('mixed'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('salivary-carcinoma-nos')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.salivarni_karcinom_nos_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('oncocytic-adenocarcinoma'),
                                    t('intestinal-type-adenocarcinoma'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('salivary-duct-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('myoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('carcinoma-ex-pleomorphic-adenoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.karcinom_z_pleomorfniho_adenomu_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('intracapsular'),
                                    t('minimally-invasive'),
                                    t('invasive'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('carcinosarcoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('poorly-differentiated-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <SimpleCheckboxes
                                dbLabel={
                                    dbLabels.spatne_diferencovany_karcinom_otevrena
                                }
                                data={formData}
                                setFormData={setFormData}
                                enableSingleSelect={true}
                                options={[
                                    t('undifferentiated-carcinoma'),
                                    t('large-cell-neuroendocrine-carcinoma'),
                                    t('small-cell-neuroendocrine-carcinoma'),
                                    t('subtype-not-specified'),
                                ]}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                        <ConditionalCheckboxOption
                            label={t('lymphoepithelial-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('squamous-cell-carcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('microsecretory-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('sclerosing-microcystic-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('mucinous-adenocarcinoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('asialoblastoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t('malt-lymphoma')}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t('no')}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
        </div>
    )
}

export default ParotidMalignantGlandDiagnosis
