import React from 'react'
import { dbLabels } from '../../../../constants'
import { GlandComponentProps } from '../../../../types'
import getDataFromPatientInterface from '../../../../utils/getDataFromPatientInterface'
import ConditionalCheckboxOption from '../../conditional-checkbox-option'
import ConditionalCheckboxes from '../../conditional-checkboxes'
import DatePicker from '../../date-picker'
import SimpleCheckboxes from '../../simple-checkboxes'
import TextInput from '../../text-input'
import { useTranslation } from 'react-i18next'
import { formTranslationKeys } from '../../../../translations'

const SubmandibularBenignGlandDiagnosis: React.FC<GlandComponentProps> = ({
    formData,
    setFormData,
    disabled,
}) => {
    const { t } = useTranslation()

    return (
        <div className="sectionDiv">
            <h1>{t(formTranslationKeys.diagnosisTitle)}</h1>
            <DatePicker
                label={t(formTranslationKeys.yearOfDiagnosis)}
                dbLabel={dbLabels.rok_diagnozy}
                data={getDataFromPatientInterface(
                    formData,
                    dbLabels.rok_diagnozy
                )}
                setFormData={setFormData}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.sideOfFinding)}
                dbLabel={dbLabels.strana_nalezu}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={[
                    t(formTranslationKeys.sideRight),
                    t(formTranslationKeys.sideLeft),
                    t(formTranslationKeys.bilateraly),
                ]}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.functionOfNVIIPreoperative)}
                dbLabel={dbLabels.funkce_n_vii_dle_h_b_predoperacne}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
                options={['I', 'II', 'III', 'IV', 'V', 'VI']}
                disabled={disabled}
            />
            <SimpleCheckboxes
                title={t(formTranslationKeys.diagnosticMethodsUsed)}
                dbLabel={dbLabels.diagnosticke_metody}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={false}
                options={[
                    t(formTranslationKeys.ultrasound),
                    t(formTranslationKeys.ct),
                    t(formTranslationKeys.mri),
                    t(formTranslationKeys.petCt),
                    t(formTranslationKeys.petMr),
                    t(formTranslationKeys.noImagingExam),
                ]}
                disabled={disabled}
            />
            <ConditionalCheckboxes
                title={t(formTranslationKeys.fnab)}
                dbLabel={dbLabels.fnab}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <SimpleCheckboxes
                        title={t(formTranslationKeys.fnabResultMSRSGC)}
                        dbLabel={dbLabels.vysledek_fnab}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                        options={[
                            t('I-fnab-result-i'),
                            t(formTranslationKeys.IINonTumor),
                            t(
                                formTranslationKeys.IIIAtypiaOfUncertainSignificance
                            ),
                            t(formTranslationKeys.IVaIVaTumorBenign),
                            t(
                                formTranslationKeys.IVbTumorOfUncertainMalignantPotential
                            ),
                            t('V-suspect-for-malignancy'),
                            t(formTranslationKeys.VITumorMalignant),
                        ]}
                        disabled={disabled}
                    />
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.coreBiopsy)}
                dbLabel={dbLabels.core_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.coreBiopsyResult)}
                        dbLabel={dbLabels.core_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.pleomorphicAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.papillaryCystadenolymphomaWarthin
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultBasalCellAdenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.myoepithelioma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.oncocytoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.canalicularAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.sebaceousAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.ductalPapilloma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.debacellousLymphadenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.keratocyst)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.other)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <TextInput
                                label={t(
                                    formTranslationKeys.histologicalTypeSpecification
                                )}
                                dbLabel={dbLabels.core_vysledek_jine}
                                data={getDataFromPatientInterface(
                                    formData,
                                    dbLabels.core_vysledek_jine
                                )}
                                setFormData={setFormData}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
            <ConditionalCheckboxes
                title={t(formTranslationKeys.openBiopsy)}
                dbLabel={dbLabels.otevrena_biopsie}
                data={formData}
                setFormData={setFormData}
                enableSingleSelect={true}
            >
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.yes)}
                    disabled={disabled}
                    setFormData={setFormData}
                >
                    <ConditionalCheckboxes
                        title={t(formTranslationKeys.openBiopsyResult)}
                        dbLabel={dbLabels.otevrena_vysledek}
                        data={formData}
                        setFormData={setFormData}
                        enableSingleSelect={true}
                    >
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.pleomorphicAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.papillaryCystadenolymphomaWarthin
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.coreResultBasalCellAdenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.myoepithelioma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.oncocytoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.canalicularAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.sebaceousAdenoma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.ductalPapilloma)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(
                                formTranslationKeys.debacellousLymphadenoma
                            )}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.keratocyst)}
                            disabled={disabled}
                            setFormData={setFormData}
                        />
                        <ConditionalCheckboxOption
                            label={t(formTranslationKeys.other)}
                            disabled={disabled}
                            setFormData={setFormData}
                        >
                            <TextInput
                                label={t(
                                    formTranslationKeys.histologicalTypeSpecification
                                )}
                                dbLabel={dbLabels.otevrena_vysledek_jine}
                                data={getDataFromPatientInterface(
                                    formData,
                                    dbLabels.otevrena_vysledek_jine
                                )}
                                setFormData={setFormData}
                                disabled={disabled}
                            />
                        </ConditionalCheckboxOption>
                    </ConditionalCheckboxes>
                </ConditionalCheckboxOption>
                <ConditionalCheckboxOption
                    label={t(formTranslationKeys.no)}
                    disabled={disabled}
                    setFormData={setFormData}
                />
            </ConditionalCheckboxes>
        </div>
    )
}

export default SubmandibularBenignGlandDiagnosis
