import { expect, test } from '@jest/globals'
import isCzechAlphabet from '../src/frontend/utils/isCzechAlphabet'

test('Check isCzechAlphabet', () => {
    const czechAlphabet = [
        'A',
        'Á',
        'B',
        'C',
        'Č',
        'D',
        'Ď',
        'E',
        'É',
        'Ě',
        'F',
        'G',
        'H',
        'Ch',
        'I',
        'Í',
        'J',
        'K',
        'L',
        'M',
        'N',
        'Ň',
        'O',
        'Ó',
        'P',
        'Q',
        'R',
        'Ř',
        'S',
        'Š',
        'T',
        'Ť',
        'U',
        'Ú',
        'Ů',
        'V',
        'W',
        'X',
        'Y',
        'Ý',
        'Z',
        'Ž',
        'a',
        'á',
        'b',
        'c',
        'č',
        'd',
        'ď',
        'e',
        'é',
        'ě',
        'f',
        'g',
        'h',
        'ch',
        'i',
        'í',
        'j',
        'k',
        'l',
        'm',
        'n',
        'ň',
        'o',
        'ó',
        'p',
        'q',
        'r',
        'ř',
        's',
        'š',
        't',
        'ť',
        'u',
        'ú',
        'ů',
        'v',
        'w',
        'x',
        'y',
        'ý',
        'z',
        'ž',
    ]

    czechAlphabet.forEach((letter) => {
        expect(isCzechAlphabet(letter)).toBe(true)
    })

    const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
    numbers.forEach((number) => {
        expect(isCzechAlphabet(number)).toBe(false)
    })
})
