name: Release

on: [release]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Setup NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: 20
          - run: npm install
          - run: npm run publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
