name: Release

on:
    release:
        types: [created, edited]
jobs:
    release:
        strategy:
            matrix:
                os: [windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - run: npm install
            - run: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    release_arm64:
#        runs-on: self-hosted
#        steps:
#            - name: Check out repository code
#              uses: actions/checkout@v4
#            - run: npm install
#            - run: npm run publish
#              env:
#                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
