name: Release

on: 
    release:
        types:
          - created
jobs:
    release:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
          - name: Check out repository code
            uses: actions/checkout@v4
          - name: Setup NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: 20
          - run: npm install
          - run: |
              if [ "${{ matrix.os }}" = "macos-latest" ]; then
                npm install --save-dev appdmg
              fi
          - run: npm run publish
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
