name: Release and Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            tag_name: ${{ steps.tag.outputs.name }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract tag name
              id: tag
              run: echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

            - name: Check that release notes exist
              run: |
                  FILE="release_notes/${{ steps.tag.outputs.name }}.md"
                  if [ ! -f "$FILE" ]; then
                    echo "❌ Release notes not found: $FILE"
                    exit 1
                  fi

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.tag.outputs.name }}
                  name: Version ${{ steps.tag.outputs.name }}
                  body_path: release_notes/${{ steps.tag.outputs.name }}.md
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish:
        needs: release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'

            - run: npm install

            - run: npm run publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
