name: Build

on: [pull_request]

jobs:
    prettier_eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm install
            - run: npm run lint
            - run: npm run prettier
            - run: npm run prettier:fix
            - run: npm run test
